### ISSUE TITLE
get_file_age function will not work on MacOS

### ISSUE THREAD

**Issue by Hudson-Hu** [aaronpowell/tmux-weather#11]
https://github.com/aaronpowell/tmux-weather/blob/a954fe15c152d6be600bca4458dd4190c8b611b5/scripts/helpers.sh#L24

get_file_age uses `stat -c` to get file age, however, the BSD `stat` does not support `-c` argument:

> stat: illegal option -- c

Maybe add a short paragraph on README.md to instruct MacOS users to have GNU `stat` installed to make this plugin work?

**Comment by aaronpowell** [comment]
There was an outsanding PR that changed this: https://github.com/aaronpowell/tmux-weather/blob/master/scripts/helpers.sh#L25-L29

Does that fix the problem? Otherwise feel free to send a PR to fix it

**Comment by Hudson-Hu** [comment]
> There was an outsanding PR that changed this: https://github.com/aaronpowell/tmux-weather/blob/master/scripts/helpers.sh#L25-L29
> 
> Does that fix the problem? Otherwise feel free to send a PR to fix it

Thanks for the swift response! Yes this PR fixed the issue perfectly.
